# Generated by Django 2.0 on 2018-03-05 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('influencer', models.CharField(max_length=50)),
                ('tweeturl', models.URLField()),
                ('subject', models.CharField(max_length=50)),
                ('retweets', models.IntegerField()),
                ('likes', models.IntegerField()),
                ('views', models.IntegerField()),
                ('sentiment', models.CharField(max_length=30)),
                ('quote', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='tweettable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excelApp.tweet')),
            ],
        ),
    ]
